FROM python:3.11-slim
WORKDIR /project
COPY requirements-backend.txt .
RUN pip install --no-cache-dir -r requirements-backend.txt
COPY src/ /project/src/
WORKDIR /project/src
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
